#!/usr/bin/env bash
# Rebuild icon-library.js from upstream Simple Icons (CC0) and Lucide (MIT).
# Usage: ./scripts/build-icon-library.sh
#
# To add icons, edit the SIMPLE_ICONS / LUCIDE_ICONS arrays below.
# Slugs come from:
#   - https://github.com/simple-icons/simple-icons/tree/master/icons (lowercased, no symbols)
#   - https://lucide.dev/icons/  (kebab-case)

set -euo pipefail

cd "$(dirname "$0")/.."

# ── Curated icon list ────────────────────────────────────────────────────────
SIMPLE_ICONS=(
  github gitlab npm gitpod stackblitz codesandbox jsdelivr unpkg
  jupyter
  socket  # saved as simple:socketdotdev — see ALIASES below
  docker  postgresql  mysql  mongodb  redis  sqlite
  visualstudiocode    # saved as simple:vscode — see ALIASES below
  nodedotjs  python  rust  go  typescript  javascript
  cloudflare  vercel  netlify
)

# Some Simple Icons slugs differ from how we want to name them. The format is
# "<upstream-slug>:<our-name>". Our internal key becomes "simple:<our-name>".
SIMPLE_ALIASES=(
  "socket:socketdotdev"
  "visualstudiocode:vscode"
)

LUCIDE_ICONS=(
  globe eye file-text code cloud zap package link shield play scale
  archive search external-link terminal layers book network bug rocket
  database server key lock mail download upload refresh-cw settings
  info triangle-alert copy plus check x book-open file-code share-2
  bookmark star heart lightbulb hash chart-bar gauge map-pin
)

# ── Fetch SVGs ───────────────────────────────────────────────────────────────
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/simple" "$TMP/lucide"

echo "→ Downloading Simple Icons..."
for slug in "${SIMPLE_ICONS[@]}"; do
  url="https://raw.githubusercontent.com/simple-icons/simple-icons/master/icons/${slug}.svg"
  outname="$slug"
  for alias in "${SIMPLE_ALIASES[@]}"; do
    src="${alias%%:*}"; dst="${alias##*:}"
    if [[ "$slug" == "$src" ]]; then outname="$dst"; break; fi
  done
  if curl -fsSL "$url" -o "$TMP/simple/${outname}.svg"; then
    echo "  ✓ simple:${outname}"
  else
    echo "  ✗ simple:${slug} (404 — check upstream slug)"
  fi
done

echo "→ Downloading Lucide..."
for slug in "${LUCIDE_ICONS[@]}"; do
  url="https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/${slug}.svg"
  if curl -fsSL "$url" -o "$TMP/lucide/${slug}.svg"; then
    echo "  ✓ lucide:${slug}"
  else
    echo "  ✗ lucide:${slug} (404 — check upstream slug)"
  fi
done

# ── Generate icon-library.js ─────────────────────────────────────────────────
echo "→ Building icon-library.js..."
TMP_DIR="$TMP" node --input-type=module -e '
import fs from "node:fs";
import path from "node:path";
const TMP = process.env.TMP_DIR;

function normalize(raw, kind) {
  let s = raw.replace(/\s+/g, " ").trim().replace(/<title>[^<]*<\/title>/g, "");
  s = s.replace(/<svg([^>]*)>/, (_, attrs) => {
    let a = attrs.replace(/\s(width|height|role)="[^"]*"/g, "");
    if (kind === "simple" && !/fill=/.test(a)) a += " fill=\"currentColor\"";
    return `<svg width="1em" height="1em" aria-hidden="true"${a}>`;
  });
  if (kind === "simple") {
    s = s.replace(/<path([^>]*)\/>/g, (_, attrs) => {
      const a = attrs.replace(/\sfill="[^"]*"/, "");
      return `<path${a} fill="currentColor"/>`;
    });
  }
  return s;
}

const lib = {};
for (const kind of ["simple", "lucide"]) {
  const dir = path.join(TMP, kind);
  if (!fs.existsSync(dir)) continue;
  for (const f of fs.readdirSync(dir).sort()) {
    if (!f.endsWith(".svg")) continue;
    const slug = f.replace(/\.svg$/, "");
    lib[`${kind}:${slug}`] = {
      label: slug,
      category: kind,
      svg: normalize(fs.readFileSync(path.join(dir, f), "utf8"), kind)
    };
  }
}

const header =
  "// Auto-generated by scripts/build-icon-library.sh — do not edit by hand.\n" +
  "// simple:* icons from Simple Icons (CC0): https://simpleicons.org/\n" +
  "// lucide:* icons from Lucide (MIT): https://lucide.dev/\n" +
  "// SVGs normalized to width/height = 1em and currentColor fill/stroke.\n\n";
fs.writeFileSync("icon-library.js", header + "export const ICON_LIBRARY = " + JSON.stringify(lib, null, 2) + ";\n");
console.log(`  wrote icon-library.js with ${Object.keys(lib).length} icons (${(fs.statSync("icon-library.js").size/1024).toFixed(1)} KB)`);
'

echo "✓ Done."
